openapi: 3.0.3
info:
  title: MedScheduler API
  description: |
    API simple et directe pour la gestion des rendez-vous médicaux et des patients.

    ## Authentification HMAC-SHA256
    Cette API utilise une authentification par signature HMAC-SHA256 ultra-sécurisée.

    ### Headers requis pour chaque requête:
    - `X-Client-ID`: Identifiant du client (medscheduler_client)
    - `X-Timestamp`: Timestamp Unix de la requête
    - `X-Signature`: Signature HMAC-SHA256 calculée

    ### Calcul de la signature:
    1. Créer la chaîne à signer: `{METHOD}\n{PATH}\n{TIMESTAMP}\n{BODY}`
    2. Calculer HMAC-SHA256 avec la clé secrète
    3. Encoder en Base64

    ### Protection contre replay attacks:
    - Les signatures expirent après 5 minutes
    - Chaque timestamp ne peut être utilisé qu'une fois

    ## Fonctionnalités
    - Gestion des patients
    - Gestion des rendez-vous médicaux
    - Format JSON simple et direct
    - Endpoint helper pour générer les signatures

  version: 1.1.0
  contact:
    name: MedScheduler Support
    email: support@medscheduler.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
  - url: https://medscheduler-api.onrender.com
    description: Serveur de production

security:
  - HMACAuth: []

paths:
  /health:
    get:
      summary: Vérification de santé de l'API
      description: Endpoint pour vérifier que l'API fonctionne correctement
      tags:
        - Health
      security: []
      responses:
        "200":
          description: API opérationnelle
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: healthy
                  api:
                    type: string
                    example: MedScheduler
                  version:
                    type: string
                    example: 1.1.0
                  authentication:
                    type: string
                    example: HMAC-SHA256 Signature
                  timestamp:
                    type: string
                    description: "Format: DD/MM/YYYY HH:MM:SS"
                    example: 26/09/2025 17:31:47

  /patients:
    get:
      summary: Récupérer tous les patients
      description: Retourne la liste complète des patients enregistrés
      tags:
        - Patients
      responses:
        "200":
          description: Liste des patients récupérée avec succès
          content:
            application/json:
              schema:
                type: object
                properties:
                  patients:
                    type: array
                    items:
                      $ref: "#/components/schemas/Patient"
                  total:
                    type: integer
                    example: 2
        "401":
          $ref: "#/components/responses/UnauthorizedError"

    post:
      summary: Créer un nouveau patient
      description: Ajoute un nouveau patient au système
      tags:
        - Patients
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PatientCreate"
      responses:
        "201":
          description: Patient créé avec succès
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Patient"
        "400":
          description: Données invalides
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "401":
          $ref: "#/components/responses/UnauthorizedError"

  /patients/{patient_id}:
    get:
      summary: Récupérer un patient spécifique
      description: Retourne les informations détaillées d'un patient
      tags:
        - Patients
      parameters:
        - name: patient_id
          in: path
          required: true
          description: Identifiant unique du patient
          schema:
            type: string
            example: pat_001
      responses:
        "200":
          description: Patient trouvé
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Patient"
        "404":
          description: Patient non trouvé
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "401":
          $ref: "#/components/responses/UnauthorizedError"

  /appointments:
    get:
      summary: Récupérer tous les rendez-vous
      description: Retourne la liste des rendez-vous, avec filtrage optionnel par date
      tags:
        - Rendez-vous
      parameters:
        - name: date
          in: query
          required: false
          description: Filtrer par date (format YYYY-MM-DD)
          schema:
            type: string
            pattern: "^\\d{2}[-/]\\d{2}[-/]\\d{4}$"
            example: 20-03-2024
      responses:
        "200":
          description: Liste des rendez-vous récupérée avec succès
          content:
            application/json:
              schema:
                type: object
                properties:
                  appointments:
                    type: array
                    items:
                      $ref: "#/components/schemas/Appointment"
                  total:
                    type: integer
                    example: 2
        "401":
          $ref: "#/components/responses/UnauthorizedError"

    post:
      summary: Créer un nouveau rendez-vous
      description: Ajoute un nouveau rendez-vous au système
      tags:
        - Rendez-vous
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AppointmentCreate"
      responses:
        "201":
          description: Rendez-vous créé avec succès
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Appointment"
        "400":
          description: Données invalides
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "401":
          $ref: "#/components/responses/UnauthorizedError"

  /appointments/{appointment_id}:
    get:
      summary: Récupérer un rendez-vous spécifique
      description: Retourne les informations détaillées d'un rendez-vous
      tags:
        - Rendez-vous
      parameters:
        - name: appointment_id
          in: path
          required: true
          description: Identifiant unique du rendez-vous
          schema:
            type: string
            example: apt_001
      responses:
        "200":
          description: Rendez-vous trouvé
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Appointment"
        "404":
          description: Rendez-vous non trouvé
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "401":
          $ref: "#/components/responses/UnauthorizedError"

    put:
      summary: Mettre à jour un rendez-vous
      description: Modifie les informations d'un rendez-vous existant
      tags:
        - Rendez-vous
      parameters:
        - name: appointment_id
          in: path
          required: true
          description: Identifiant unique du rendez-vous
          schema:
            type: string
            example: apt_001
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AppointmentUpdate"
      responses:
        "200":
          description: Rendez-vous mis à jour avec succès
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Appointment"
        "404":
          description: Rendez-vous non trouvé
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "401":
          $ref: "#/components/responses/UnauthorizedError"

  /availabilities:
    get:
      summary: Récupérer les disponibilités des médecins
      description: Retourne la liste des créneaux disponibles, avec filtrage optionnel par date ou médecin
      tags:
        - Disponibilités
      parameters:
        - name: date
          in: query
          required: false
          description: Filtrer par date (format YYYY-MM-DD)
          schema:
            type: string
            pattern: "^\\d{4}-\\d{2}-\\d{2}$"
            example: 2024-03-20
        - name: doctor_name
          in: query
          required: false
          description: Filtrer par nom de médecin
          schema:
            type: string
            example: Dr. Leblanc
      responses:
        "200":
          description: Liste des disponibilités récupérée avec succès
          content:
            application/json:
              schema:
                type: object
                properties:
                  availabilities:
                    type: array
                    items:
                      $ref: "#/components/schemas/Availability"
                  total:
                    type: integer
                    example: 2
        "401":
          $ref: "#/components/responses/UnauthorizedError"

components:
  securitySchemes:
    HMACAuth:
      type: apiKey
      in: header
      name: X-Signature
      description: |
        Authentification HMAC-SHA256. 

        Headers requis:
        - X-Client-ID: medscheduler_client
        - X-Timestamp: timestamp Unix (ex: 1703515200)
        - X-Signature: signature HMAC calculée

        Utilisez l'endpoint /auth/signature-helper pour générer les signatures.

  responses:
    UnauthorizedError:
      description: Authentification HMAC échouée
      content:
        application/json:
          schema:
            oneOf:
              - $ref: "#/components/schemas/Error"
              - $ref: "#/components/schemas/HMACError"

  schemas:
    Patient:
      type: object
      properties:
        id:
          type: string
          description: Identifiant unique du patient
          example: pat_001
        first_name:
          type: string
          description: Prénom du patient
          example: Jean
        last_name:
          type: string
          description: Nom de famille du patient
          example: Dupont
        birthdate:
          type: string
          pattern: "^\\d{4}-\\d{2}-\\d{2}$"
          description: Date de naissance (format YYYY-MM-DD)
          example: 1985-03-15
        phone_number:
          type: string
          description: Numéro de téléphone
          example: +33123456789
        email:
          type: string
          format: email
          description: Adresse email
          example: jean.dupont@email.com
        created_at:
          type: string
          description: Date de création du dossier (format YYYY/MM/DD HH:MM:SS)
          example: 2024/01/15 10:30:00

    PatientCreate:
      type: object
      required:
        - first_name
        - last_name
        - birthdate
        - phone_number
      properties:
        first_name:
          type: string
          description: Prénom du patient
          example: Jean
        last_name:
          type: string
          description: Nom de famille du patient
          example: Dupont
        birthdate:
          type: string
          pattern: "^\\d{4}-\\d{2}-\\d{2}$"
          description: Date de naissance (format YYYY-MM-DD)
          example: 1985-03-15
        phone_number:
          type: string
          description: Numéro de téléphone
          example: +33123456789
        email:
          type: string
          format: email
          description: Adresse email (optionnel)
          example: jean.dupont@email.com

    Appointment:
      type: object
      properties:
        id:
          type: string
          description: Identifiant unique du rendez-vous
          example: apt_001
        patient_id:
          type: string
          description: Identifiant du patient
          example: pat_001
        doctor_name:
          type: string
          description: Nom du médecin
          example: Dr. Leblanc
        appointment_date:
          type: string
          pattern: "^\\d{4}-\\d{2}-\\d{2}$"
          description: Date du rendez-vous (format YYYY-MM-DD)
          example: 2024-03-20
        appointment_time:
          type: string
          description: Heure du rendez-vous (format HH:MM)
          example: "14:30"
        duration:
          type: integer
          description: Durée en minutes
          example: 30
        reason:
          type: string
          description: Raison du rendez-vous
          example: Consultation de routine
        created_at:
          type: string
          description: Date de création (format YYYY/MM/DD HH:MM:SS)
          example: 2024/01/15 11:00:00

    AppointmentCreate:
      type: object
      required:
        - patient_id
        - doctor_name
        - appointment_date
        - appointment_time
      properties:
        patient_id:
          type: string
          description: Identifiant du patient
          example: pat_001
        doctor_name:
          type: string
          description: Nom du médecin
          example: Dr. Leblanc
        appointment_date:
          type: string
          pattern: "^\\d{4}-\\d{2}-\\d{2}$"
          description: Date du rendez-vous (format YYYY-MM-DD)
          example: 2024-03-20
        appointment_time:
          type: string
          description: Heure du rendez-vous (format HH:MM)
          example: "14:30"
        duration:
          type: integer
          description: "Durée en minutes (optionnel, défaut: 30)"
          example: 30
        reason:
          type: string
          description: "Raison du rendez-vous (optionnel)"
          example: Consultation de routine

    AppointmentUpdate:
      type: object
      properties:
        doctor_name:
          type: string
          description: Nom du médecin
          example: Dr. Leblanc
        appointment_date:
          type: string
          pattern: "^\\d{4}-\\d{2}-\\d{2}$"
          description: Date du rendez-vous (format YYYY-MM-DD)
          example: 2024-03-20
        appointment_time:
          type: string
          description: Heure du rendez-vous (format HH:MM)
          example: "14:30"
        duration:
          type: integer
          description: Durée en minutes
          example: 30
        reason:
          type: string
          description: Raison du rendez-vous
          example: Consultation de routine

    Availability:
      type: object
      properties:
        id:
          type: string
          description: Identifiant unique de la disponibilité
          example: avail_001
        doctor_name:
          type: string
          description: Nom du médecin
          example: Dr. Leblanc
        date:
          type: string
          pattern: "^\\d{4}-\\d{2}-\\d{2}$"
          description: Date (format YYYY-MM-DD)
          example: 2024-03-20
        slots:
          type: array
          description: Créneaux horaires disponibles
          items:
            type: string
            example: "09:00"

    Error:
      type: object
      properties:
        error:
          type: string
          description: Message d'erreur
          example: Invalid signature

    HMACError:
      type: object
      properties:
        error:
          type: string
          description: Message d'erreur HMAC
          example: Invalid signature
        required:
          type: array
          items:
            type: string
          description: Headers requis manquants
          example: ["X-Client-ID", "X-Timestamp", "X-Signature"]
        debug_info:
          type: object
          description: Informations de débogage
          properties:
            method:
              type: string
              example: GET
            path:
              type: string
              example: /patients
            timestamp:
              type: string
              example: "1679485200"
            body_length:
              type: integer
              example: 0

tags:
  - name: Health
    description: Endpoints de santé et statut de l'API
  - name: Patients
    description: Gestion des patients
  - name: Rendez-vous
    description: Gestion des rendez-vous médicaux
  - name: Disponibilités
    description: Consultation des disponibilités des médecins
